sudo: false

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "12"

after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
