sudo: false

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "12"

install:
  - npm install --build-from-source

after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

deploy:
  provider: script
  script:
    - npm run upload-posix
  skip_cleanup: true
  on:
    tags: true
    repo: httptoolkit/node-ffi-napi
